### ISSUE TITLE
can't clone nn_menu

### ISSUE THREAD

**Issue by HaolinChen** [GreenWaves-Technologies/nn_menu#3]
I first source sourceme.sh and choose 3.
then I run sudo git clone --recurse-submodules -j4 git@github.com:GreenWaves-Technologies/nn_menu.git in the same terminal.

bitcraze@ubuntu:~/projects/gap_sdk$ sudo git clone --recurse-submodules -j4 git@github.com:GreenWaves-Technologies/nn_menu.git
Cloning into 'nn_menu'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights

How to solve this problem?

**Comment by antocad** [comment]
You can do this, It solved the problem for me:

```git clone https://github.com/GreenWaves-Technologies/nn_menu.git```

then,  in the .gitmodules file, replace all git@github.com: by https://github.com/
and finally :
git submodule sync
git submodule update --init --recursive

**Comment by HaolinChen** [comment]
That really works! Thanks!!!
